# Generated by Django 6.0.1 on 2026-03-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_date', models.DateField(db_index=True, verbose_name='Дата замены')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_replacements', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('original_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_replacements', to='api.schedulelesson', verbose_name='Исходный урок')),
                ('replacement_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_replacements', to='api.subject', verbose_name='Предмет замены')),
                ('replacement_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_replacements', to=settings.AUTH_USER_MODEL, verbose_name='Учитель замены')),
            ],
            options={
                'verbose_name': 'Разовая замена урока',
                'verbose_name_plural': 'Разовые замены уроков',
                'ordering': ['-replacement_date', 'original_lesson__lesson_number'],
                'unique_together': {('replacement_date', 'original_lesson')},
            },
        ),
    ]
