# Generated by Django 6.0.1 on 2026-01-31 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyschedule_is_weekend_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Обновление'), ('DELETE', 'Удаление (физическое)'), ('SOFT_DELETE', 'Удаление (логическое)'), ('RESTORE', 'Восстановление'), ('VIEW', 'Просмотр'), ('EXPORT', 'Экспорт'), ('IMPORT', 'Импорт'), ('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('SYSTEM', 'Системное действие')], max_length=20, verbose_name='Тип действия')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID объекта')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Старые значения')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Новые значения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь запроса')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Метод запроса')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время действия')),
                ('is_system_action', models.BooleanField(default=False, verbose_name='Системное действие')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_auditlo_user_id_8f69e8_idx'), models.Index(fields=['model_name', 'action'], name='api_auditlo_model_n_a416ae_idx'), models.Index(fields=['timestamp'], name='api_auditlo_timesta_da87a7_idx')],
            },
        ),
    ]
