# Generated by Django 6.0.1 on 2026-02-13 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('frequency', models.CharField(choices=[('hourly', 'Каждый час'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=20, verbose_name='Частота')),
                ('time', models.TimeField(default='03:00', verbose_name='Время')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True, verbose_name='День недели')),
                ('day_of_month', models.IntegerField(blank=True, help_text='1-31, отрицательные значения с конца месяца', null=True, verbose_name='День месяца')),
                ('interval_hours', models.IntegerField(default=6, help_text='Для почасового режима', verbose_name='Интервал (часы)')),
                ('keep_last', models.IntegerField(default=10, help_text='Количество последних копий для хранения', verbose_name='Хранить последних')),
                ('compression', models.BooleanField(default=True, verbose_name='Сжимать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Следующий запуск')),
            ],
            options={
                'verbose_name': 'Расписание бэкапов',
                'verbose_name_plural': 'Расписания бэкапов',
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('backup_type', models.CharField(choices=[('manual', 'Ручное'), ('auto', 'Автоматическое'), ('scheduled', 'По расписанию')], default='manual', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('restoring', 'Восстановление')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('database_name', models.CharField(blank=True, max_length=255, verbose_name='Имя БД')),
                ('tables_count', models.IntegerField(default=0, verbose_name='Количество таблиц')),
                ('row_count', models.BigIntegerField(default=0, verbose_name='Всего записей')),
                ('compression_ratio', models.FloatField(blank=True, null=True, verbose_name='Степень сжатия')),
                ('md5_hash', models.CharField(blank=True, max_length=32, verbose_name='MD5 хеш')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('restore', 'Восстановление'), ('delete', 'Удаление'), ('download', 'Скачивание')], max_length=20, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backup_service.databasebackup')),
            ],
            options={
                'verbose_name': 'Лог бэкапа',
                'verbose_name_plural': 'Логи бэкапов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
